# Generated by Django 2.2.8 on 2020-08-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizfreak', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='locked',
            field=models.DateTimeField(null=True, verbose_name='locked'),
        ),
    ]
