# Generated by Django 2.2.8 on 2020-09-30 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizfreak', '0003_result_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='public',
            field=models.BooleanField(default=True, verbose_name='public'),
        ),
    ]
